spring:
  application:
    name: book
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:/opt/db/book.db"
  ai:
    ollama:
      base-url: 'http://192.168.1.3:11434'
server:
  port: 8080
