local:
  user:
    home: ${user.home}/.picture-book
spring:
  application:
    name: picture-book
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:${local.user.home}/book.db"
ai:
  text:
     mode: 1 # 1: 通义千问 2 远程api
     remote-url: http://192.168.1.4:11434/
  image:
     mode: 1
     remote-url: http://192.168.1.4:10000/get_image_remote
  voice:
     mode: 1
     remote-url: http://192.168.1.4:10000/get_voice_remote
